/*
 * @Author: Macroyu1 1628343763@qq.com
 * @Date: 2024-01-09 16:26:16
 * @LastEditors: Macroyu1 1628343763@qq.com
 * @LastEditTime: 2024-01-13 09:02:32
 * @FilePath: /PX4-Autopilot/src/modules/pos_ctrl/pos_ctrl_params.c
 * @Description:
 *
 * Copyright (c) 2024 by HongYu Fu, All Rights Reserved.
 */

PARAM_DEFINE_FLOAT(X_P, 1.f);
PARAM_DEFINE_FLOAT(X_WC, 1.f);
PARAM_DEFINE_FLOAT(X_B0, 1.f);
PARAM_DEFINE_FLOAT(X_C2O, 6.f);


PARAM_DEFINE_FLOAT(Y_P, 1.f);
PARAM_DEFINE_FLOAT(Y_WC, 1.2f);
PARAM_DEFINE_FLOAT(Y_B0, 1.f);
PARAM_DEFINE_FLOAT(Y_C2O, 6.f);

PARAM_DEFINE_FLOAT(Z_P, 1.f);
PARAM_DEFINE_FLOAT(Z_WC, 2.f);
PARAM_DEFINE_FLOAT(Z_B0, 0.5f);
PARAM_DEFINE_FLOAT(Z_C2O, 6.f);

PARAM_DEFINE_INT32(USE_HTE, 1);
PARAM_DEFINE_FLOAT(THR_HOVER, 0.5f);

PARAM_DEFINE_FLOAT(XY_VEL_P, 1.8f);
PARAM_DEFINE_FLOAT(XY_VEL_I, 0.4f);
PARAM_DEFINE_FLOAT(XY_VEL_D, 0.2f);
PARAM_DEFINE_FLOAT(Z_VEL_P, 4.f);
PARAM_DEFINE_FLOAT(Z_VEL_I, 2.f);
PARAM_DEFINE_FLOAT(Z_VEL_D, 2.f);
